# -*- mode: ruby -*-
# vi: set ft=ruby :
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.box = "coding"
   
# Setup memory for the virtual machine
config.vm.provider "virtualbox" do |v|
	v.memory = 8000
	v.cpus = 4
end

config.vm.network "forwarded_port", guest: 8888, host: 8888
config.vm.network "forwarded_port", guest: 5000, host: 5000

config.ssh.forward_agent = true

end